import type { Metadata } from "next";
import Header from "@/components/Header";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: './DQFavicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-black`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
